'use strict';
let questions=[],lastResult=null;
const $=id=>document.getElementById(id);
const examples={age:'Akio is older than Naoko.\nAkio 比 Naoko 年長。',height:'Akio is taller than Naoko.\nAkio 比 Naoko 高。',study:'Naoko is a better student than Akio.\nNaoko 的學習表現比 Akio 好。',driving:'Naoko is a better driver than Akio.\n依教材描述，Naoko 的駕駛表現比 Akio 好。'};
function compare(){$('comparison-result').textContent=examples[$('comparison').value];}
$('comparison').addEventListener('change',compare);compare();
$('projector').addEventListener('click',()=>{const on=document.body.classList.toggle('projector');$('projector').textContent=on?'一般模式':'投影模式';$('projector').setAttribute('aria-pressed',String(on));});
function buildTrip(){const d=$('destination').value,t=$('transport').value,r=$('reason').value,s=$('stay').value;$('trip-result').textContent=`I like to spend my vacations in ${d} because it is ${r}. I like to travel by ${t} and stay in ${s}.`;}
$('trip-form').addEventListener('submit',e=>{e.preventDefault();buildTrip();});buildTrip();
$('read-aloud').addEventListener('click',()=>{if(!('speechSynthesis' in window)){$('voice-status').textContent='此瀏覽器不支援朗讀，請直接練習口說。';return;}speechSynthesis.cancel();const u=new SpeechSynthesisUtterance($('trip-result').textContent);u.lang='en-US';u.rate=.85;u.onerror=()=>{$('voice-status').textContent='語音暫時無法使用，請直接練習口說。';};speechSynthesis.speak(u);});
async function init(){try{const responses=await Promise.all([fetch('data/lesson.json'),fetch('data/questions.json')]);if(responses.some(r=>!r.ok))throw Error('load');const [lesson,q]=await Promise.all(responses.map(r=>r.json()));questions=q;
 for(const review of lesson.reviews){const a=document.createElement('article'),label=document.createElement('div'),body=document.createElement('div'),h=document.createElement('h3'),p=document.createElement('p');label.className='review-label';label.textContent=review.id;h.textContent=review.title;p.textContent=review.text;body.append(h,p);a.append(label,body);$('reviews').append(a);}
 for(const [en,zh] of lesson.vocabulary){const p=document.createElement('p'),b=document.createElement('b');b.textContent=en;p.append(b,document.createElement('br'),document.createTextNode(zh));$('vocabulary').append(p);}
 q.forEach((item,i)=>{const f=document.createElement('fieldset'),l=document.createElement('legend');l.textContent=`${i+1}. ${item.prompt}`;f.append(l);item.options.forEach((option,j)=>{const label=document.createElement('label'),input=document.createElement('input');input.type='radio';input.name='q'+i;input.value=String(j);input.required=true;label.append(input,document.createTextNode(option));f.append(label);});const feedback=document.createElement('p');feedback.id='feedback-'+i;feedback.className='feedback';feedback.hidden=true;f.append(feedback);$('questions').append(f);});
 try{const saved=JSON.parse(localStorage.getItem('business-plus-u6-result'));if(saved&&Array.isArray(saved.answers)&&saved.answers.length===q.length){saved.answers.forEach((answer,i)=>{const input=document.querySelector(`input[name="q${i}"][value="${answer}"]`);if(input)input.checked=true;});$('score').textContent='已恢復此裝置上次的答案。提交可重新查看解析。';}}catch{}
 }catch{$('load-error').hidden=false;$('load-error').textContent='課程資料載入失敗，請重新整理，並確認透過網站網址開啟。';$('quiz').querySelector('[type=submit]').disabled=true;}}
$('quiz').addEventListener('submit',e=>{e.preventDefault();const fd=new FormData(e.currentTarget);let total=0;const answers=questions.map((q,i)=>{const a=Number(fd.get('q'+i)),ok=a===q.answer;if(ok)total++;const f=$('feedback-'+i);f.hidden=false;f.className='feedback '+(ok?'correct':'incorrect');f.textContent=(ok?'✓ 正確。':'需再練習。正確答案：'+q.options[q.answer]+'。')+' '+q.explanation;return a;});lastResult={unit:'Business Plus 1 Unit 6',completedAt:new Date().toISOString(),score:total,total:questions.length,answers};$('score').textContent=`本次成績：${total} / ${questions.length}。請閱讀每題解析，再練習一次。`;try{localStorage.setItem('business-plus-u6-result',JSON.stringify(lastResult));}catch{$('score').textContent+=' 此瀏覽器無法儲存，請下載學習紀錄。';}$('export').disabled=false;$('score').scrollIntoView({behavior:'smooth',block:'center'});});
$('reset').addEventListener('click',()=>{HTMLFormElement.prototype.reset.call($('quiz'));document.querySelectorAll('.feedback').forEach(f=>f.hidden=true);$('score').textContent='已清除作答，可重新開始。';lastResult=null;$('export').disabled=true;try{localStorage.removeItem('business-plus-u6-result');}catch{}});
$('export').addEventListener('click',()=>{if(!lastResult)return;const url=URL.createObjectURL(new Blob([JSON.stringify(lastResult,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='business-plus-u6-result.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
init();
