'use strict';
let questions=[],lastResult=null;
const $=id=>document.getElementById(id);
const examples={age:'Akio is older than Naoko.',height:'Akio is taller than Naoko.',study:'Naoko is a better student than Akio.',driving:'Naoko is a better driver than Akio.'};
function compare(){$('comparison-result').textContent=examples[$('comparison').value];}
$('comparison').addEventListener('change',compare);compare();
$('projector').addEventListener('click',()=>{const on=document.body.classList.toggle('projector');$('projector').textContent=on?'Standard mode':'Projector mode';$('projector').setAttribute('aria-pressed',String(on));});
function buildTrip(){const d=$('destination').value,t=$('transport').value,r=$('reason').value,s=$('stay').value;const destinationPhrase=d==='the beach'?'at the beach':`in ${d}`;const stayPhrase=s==='a campsite'?'at a campsite':`in ${s}`;$('trip-result').textContent=`I like to spend my vacations ${destinationPhrase} because it is ${r}. I like to travel by ${t} and stay ${stayPhrase}.`;}
$('trip-form').addEventListener('submit',e=>{e.preventDefault();buildTrip();});buildTrip();
async function init(){try{const responses=await Promise.all([fetch('data/lesson.json'),fetch('data/questions.json')]);if(responses.some(r=>!r.ok))throw Error('load');const [lesson,q]=await Promise.all(responses.map(r=>r.json()));questions=q;
 for(const review of lesson.reviews){const a=document.createElement('article'),label=document.createElement('div'),body=document.createElement('div'),h=document.createElement('h3'),p=document.createElement('p');label.className='review-label';label.textContent=review.id;h.textContent=review.title;p.textContent=review.text;body.append(h,p);a.append(label,body);$('reviews').append(a);}
 for(const [word,definition] of lesson.vocabulary){const p=document.createElement('p'),b=document.createElement('b');b.textContent=word;p.append(b,document.createElement('br'),document.createTextNode(definition));$('vocabulary').append(p);}
 q.forEach((item,i)=>{const f=document.createElement('fieldset'),l=document.createElement('legend');l.textContent=`${i+1}. ${item.prompt}`;f.append(l);item.options.forEach((option,j)=>{const label=document.createElement('label'),input=document.createElement('input');input.type='radio';input.name='q'+i;input.value=String(j);input.required=true;label.append(input,document.createTextNode(option));f.append(label);});const feedback=document.createElement('p');feedback.id='feedback-'+i;feedback.className='feedback';feedback.hidden=true;f.append(feedback);$('questions').append(f);});
 try{const saved=JSON.parse(localStorage.getItem('business-plus-u6-result'));if(saved&&Array.isArray(saved.answers)&&saved.answers.length===q.length){saved.answers.forEach((answer,i)=>{const input=document.querySelector(`input[name="q${i}"][value="${answer}"]`);if(input)input.checked=true;});$('score').textContent='Your previous answers have been restored. Submit to review the explanations.';}}catch{}
 }catch{$('load-error').hidden=false;$('load-error').textContent='The lesson could not be loaded. Refresh the page and make sure you are using the website URL.';$('quiz').querySelector('[type=submit]').disabled=true;}}
$('quiz').addEventListener('submit',e=>{e.preventDefault();const fd=new FormData(e.currentTarget);let total=0;const answers=questions.map((q,i)=>{const a=Number(fd.get('q'+i)),ok=a===q.answer;if(ok)total++;const f=$('feedback-'+i);f.hidden=false;f.className='feedback '+(ok?'correct':'incorrect');f.textContent=(ok?'✓ Correct.':'Try again. Correct answer: '+q.options[q.answer]+'.')+' '+q.explanation;return a;});lastResult={unit:'Business Plus 1 Unit 6',completedAt:new Date().toISOString(),score:total,total:questions.length,answers};$('score').textContent=`Your score: ${total} / ${questions.length}. Read each explanation, then try again.`;try{localStorage.setItem('business-plus-u6-result',JSON.stringify(lastResult));}catch{$('score').textContent+=' This browser cannot save your answers. Please download your results.';}$('export').disabled=false;$('score').scrollIntoView({behavior:'smooth',block:'center'});});
$('reset').addEventListener('click',()=>{HTMLFormElement.prototype.reset.call($('quiz'));document.querySelectorAll('.feedback').forEach(f=>f.hidden=true);$('score').textContent='Your answers have been cleared. You can start again.';lastResult=null;$('export').disabled=true;try{localStorage.removeItem('business-plus-u6-result');}catch{}});
$('export').addEventListener('click',()=>{if(!lastResult)return;const url=URL.createObjectURL(new Blob([JSON.stringify(lastResult,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='business-plus-u6-result.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
init();

async function initListening(){try{const response=await fetch('data/track32.json');if(!response.ok)throw Error('load');const exercise=await response.json();exercise.items.forEach((item,i)=>{const field=document.createElement('fieldset'),legend=document.createElement('legend');legend.textContent=(i+1)+'. '+item.statement;field.append(legend);for(const choice of ['Do','Don’t']){const label=document.createElement('label'),input=document.createElement('input');input.type='radio';input.name='listen'+i;input.value=choice;input.required=true;label.append(input,document.createTextNode(choice));field.append(label);}const feedback=document.createElement('p');feedback.className='feedback';feedback.hidden=true;feedback.id='listen-feedback-'+i;field.append(feedback);$('listening-questions').append(field);});$('listening-form').addEventListener('submit',event=>{event.preventDefault();const answers=new FormData(event.currentTarget);let score=0;exercise.items.forEach((item,i)=>{const correct=answers.get('listen'+i)===item.answer;if(correct)score++;const feedback=$('listen-feedback-'+i);feedback.hidden=false;feedback.className='feedback '+(correct?'correct':'incorrect');feedback.textContent=correct?'✓ Correct.':'Correct answer: '+item.answer+'.';});$('listening-score').hidden=false;$('listening-score').textContent='Your listening score: '+score+' / '+exercise.items.length;});$('listening-reset').addEventListener('click',()=>{HTMLFormElement.prototype.reset.call($('listening-form'));$('listening-score').hidden=true;$('listening-form').querySelectorAll('.feedback').forEach(p=>p.hidden=true);});}catch{$('listening-score').hidden=false;$('listening-score').textContent='The listening exercise could not be loaded. Please refresh the page.';$('listening-form').querySelector('[type=submit]').disabled=true;}}
initListening();

async function initPlaces(){
 const form=$('places-form'),status=$('places-score');form.noValidate=true;
 try{
  const response=await fetch('data/places.json');if(!response.ok)throw Error('load');const data=await response.json();
  data.questions.forEach((item,i)=>{
   const field=document.createElement('fieldset'),legend=document.createElement('legend');legend.textContent=(i+1)+'. '+item.statement;field.append(legend);
   for(const choice of ['True','False']){const label=document.createElement('label'),input=document.createElement('input');input.type='radio';input.name='place'+i;input.value=choice;label.append(input,document.createTextNode(choice));field.append(label);}
   const label=document.createElement('label'),correction=document.createElement('textarea');label.textContent='If false, write a corrected sentence:';label.htmlFor='place-correction-'+i;correction.id=label.htmlFor;correction.rows=2;correction.placeholder='Your corrected sentence';field.append(label,correction);
   const feedback=document.createElement('p');feedback.id='place-feedback-'+i;feedback.className='feedback';feedback.hidden=true;field.append(feedback);$('places-questions').append(field);
  });
  form.addEventListener('submit',event=>{
   event.preventDefault();const answers=new FormData(form);let score=0,unanswered=0;
   data.questions.forEach((item,i)=>{const answer=answers.get('place'+i),correct=answer===(item.answer?'True':'False');if(!answer)unanswered++;if(correct)score++;const feedback=$('place-feedback-'+i);feedback.hidden=false;feedback.className='feedback '+(correct?'correct':'incorrect');feedback.textContent=!answer?'Choose True or False for this question.':(correct?'✓ Correct. ':'Correct answer: '+(item.answer?'True':'False')+'. ')+item.explanation;});
   status.hidden=false;status.textContent='True/False score: '+score+' / '+data.questions.length+'. '+(unanswered?unanswered+' unanswered. Choose an answer for each question, then check again.':'Compare your written corrections with the model sentences above. Written corrections are for self-review.');status.scrollIntoView({block:'center',behavior:'smooth'});
  });
  $('places-reset').addEventListener('click',()=>{form.querySelectorAll('input[type=radio]').forEach(input=>input.checked=false);form.querySelectorAll('textarea').forEach(input=>input.value='');form.querySelectorAll('.feedback').forEach(p=>p.hidden=true);status.hidden=false;status.textContent='Answers cleared. You can try again.';});
 }catch{status.hidden=false;status.textContent='The place comparison exercise could not be loaded. Please refresh the page.';form.querySelector('[type=submit]').disabled=true;}
}
initPlaces();
