'use strict';
let questions=[],lastResult=null;
const $=id=>document.getElementById(id);
const examples={age:'Akio is older than Naoko.',height:'Akio is taller than Naoko.',study:'Naoko is a better student than Akio.',driving:'Naoko is a better driver than Akio.'};
function compare(){$('comparison-result').textContent=examples[$('comparison').value];}
$('comparison').addEventListener('change',compare);compare();
$('projector').addEventListener('click',()=>{const on=document.body.classList.toggle('projector');$('projector').textContent=on?'Standard mode':'Projector mode';$('projector').setAttribute('aria-pressed',String(on));});
function buildTrip(){const d=$('destination').value,t=$('transport').value,r=$('reason').value,s=$('stay').value;$('trip-result').textContent=`I like to spend my vacations in ${d} because it is ${r}. I like to travel by ${t} and stay in ${s}.`;}
$('trip-form').addEventListener('submit',e=>{e.preventDefault();buildTrip();});buildTrip();
$('read-aloud').addEventListener('click',()=>{if(!('speechSynthesis' in window)){$('voice-status').textContent='This browser does not support read aloud. Practice speaking the example yourself.';return;}speechSynthesis.cancel();const u=new SpeechSynthesisUtterance($('trip-result').textContent);u.lang='en-US';u.rate=.85;u.onerror=()=>{$('voice-status').textContent='Speech is unavailable. Practice speaking the example yourself.';};speechSynthesis.speak(u);});
async function init(){try{const responses=await Promise.all([fetch('data/lesson.json'),fetch('data/questions.json')]);if(responses.some(r=>!r.ok))throw Error('load');const [lesson,q]=await Promise.all(responses.map(r=>r.json()));questions=q;
 for(const review of lesson.reviews){const a=document.createElement('article'),label=document.createElement('div'),body=document.createElement('div'),h=document.createElement('h3'),p=document.createElement('p');label.className='review-label';label.textContent=review.id;h.textContent=review.title;p.textContent=review.text;body.append(h,p);a.append(label,body);$('reviews').append(a);}
 for(const [word,definition] of lesson.vocabulary){const p=document.createElement('p'),b=document.createElement('b');b.textContent=word;p.append(b,document.createElement('br'),document.createTextNode(definition));$('vocabulary').append(p);}
 q.forEach((item,i)=>{const f=document.createElement('fieldset'),l=document.createElement('legend');l.textContent=`${i+1}. ${item.prompt}`;f.append(l);item.options.forEach((option,j)=>{const label=document.createElement('label'),input=document.createElement('input');input.type='radio';input.name='q'+i;input.value=String(j);input.required=true;label.append(input,document.createTextNode(option));f.append(label);});const feedback=document.createElement('p');feedback.id='feedback-'+i;feedback.className='feedback';feedback.hidden=true;f.append(feedback);$('questions').append(f);});
 try{const saved=JSON.parse(localStorage.getItem('business-plus-u6-result'));if(saved&&Array.isArray(saved.answers)&&saved.answers.length===q.length){saved.answers.forEach((answer,i)=>{const input=document.querySelector(`input[name="q${i}"][value="${answer}"]`);if(input)input.checked=true;});$('score').textContent='Your previous answers have been restored. Submit to review the explanations.';}}catch{}
 }catch{$('load-error').hidden=false;$('load-error').textContent='The lesson could not be loaded. Refresh the page and make sure you are using the website URL.';$('quiz').querySelector('[type=submit]').disabled=true;}}
$('quiz').addEventListener('submit',e=>{e.preventDefault();const fd=new FormData(e.currentTarget);let total=0;const answers=questions.map((q,i)=>{const a=Number(fd.get('q'+i)),ok=a===q.answer;if(ok)total++;const f=$('feedback-'+i);f.hidden=false;f.className='feedback '+(ok?'correct':'incorrect');f.textContent=(ok?'✓ Correct.':'Try again. Correct answer: '+q.options[q.answer]+'.')+' '+q.explanation;return a;});lastResult={unit:'Business Plus 1 Unit 6',completedAt:new Date().toISOString(),score:total,total:questions.length,answers};$('score').textContent=`Your score: ${total} / ${questions.length}. Read each explanation, then try again.`;try{localStorage.setItem('business-plus-u6-result',JSON.stringify(lastResult));}catch{$('score').textContent+=' This browser cannot save your answers. Please download your results.';}$('export').disabled=false;$('score').scrollIntoView({behavior:'smooth',block:'center'});});
$('reset').addEventListener('click',()=>{HTMLFormElement.prototype.reset.call($('quiz'));document.querySelectorAll('.feedback').forEach(f=>f.hidden=true);$('score').textContent='Your answers have been cleared. You can start again.';lastResult=null;$('export').disabled=true;try{localStorage.removeItem('business-plus-u6-result');}catch{}});
$('export').addEventListener('click',()=>{if(!lastResult)return;const url=URL.createObjectURL(new Blob([JSON.stringify(lastResult,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='business-plus-u6-result.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
init();
